create table if not exists public.internal_payment_reports (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  influencer_id bigint references public.influencers(id) on delete set null,
  from_date date,
  to_date date,
  title text not null,
  share_token text not null unique,
  created_at timestamp with time zone not null default now()
);

create index if not exists internal_payment_reports_created_at_idx
  on public.internal_payment_reports (created_at desc);

alter table public.internal_payment_reports enable row level security;

drop policy if exists "admin all internal_payment_reports" on public.internal_payment_reports;

create policy "admin all internal_payment_reports"
  on public.internal_payment_reports
  for all
  to authenticated
  using (true)
  with check (true);

grant all on table public.internal_payment_reports to authenticated;
grant all on table public.internal_payment_reports to service_role;
grant usage, select on sequence public.internal_payment_reports_id_seq to authenticated;
grant usage, select on sequence public.internal_payment_reports_id_seq to service_role;
