create table if not exists public.line_contacts (
  id bigint generated by default as identity primary key,
  line_user_id text not null unique,
  source_type text,
  display_name text,
  picture_url text,
  status_message text,
  last_message_text text,
  last_event_type text,
  last_received_at timestamp with time zone not null default now(),
  linked_influencer_id bigint references public.influencers(id) on delete set null,
  linked_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists line_contacts_last_received_at_idx
  on public.line_contacts (last_received_at desc);

create index if not exists line_contacts_linked_influencer_id_idx
  on public.line_contacts (linked_influencer_id);

alter table public.line_contacts enable row level security;

drop policy if exists "admin all line_contacts" on public.line_contacts;

create policy "admin all line_contacts"
  on public.line_contacts
  for all
  to authenticated
  using (true)
  with check (true);

grant all on table public.line_contacts to authenticated;
grant all on table public.line_contacts to service_role;
grant usage, select on sequence public.line_contacts_id_seq to authenticated;
grant usage, select on sequence public.line_contacts_id_seq to service_role;
