create extension if not exists pg_net;

do $$
begin
  perform extensions.grant_pg_net_access();
exception
  when others then
    null;
end
$$;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  locale text,
  user_agent text,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.notify_influencer_application_push()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_url text;
  webhook_secret text;
begin
  if coalesce(new.status, 'pending') <> 'pending' then
    return new;
  end if;

  select value into base_url
  from public.app_settings
  where key = 'web_push_app_base_url';

  select value into webhook_secret
  from public.app_settings
  where key = 'web_push_applicant_webhook_secret';

  if coalesce(base_url, '') = '' or coalesce(webhook_secret, '') = '' then
    return new;
  end if;

  perform net.http_post(
    url := rtrim(base_url, '/') || '/api/push/applicant',
    body := jsonb_build_object(
      'type', 'INSERT',
      'schema', 'public',
      'table', 'influencer_applications',
      'record', to_jsonb(new)
    ),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-push-webhook-secret', webhook_secret
    ),
    timeout_milliseconds := 2000
  );

  return new;
exception
  when others then
    raise log 'notify_influencer_application_push failed: %', sqlerrm;
    return new;
end;
$$;

drop trigger if exists influencer_applications_push_notify on public.influencer_applications;

create trigger influencer_applications_push_notify
after insert on public.influencer_applications
for each row
execute function public.notify_influencer_application_push();
