create table if not exists public.shared_reports (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  year_month text not null,
  title text not null,
  share_token text not null unique,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists shared_reports_client_month_key
  on public.shared_reports (client_id, year_month);

alter table public.shared_reports enable row level security;

drop policy if exists "admin all shared_reports" on public.shared_reports;

create policy "admin all shared_reports"
  on public.shared_reports
  for all
  to authenticated
  using (true)
  with check (true);

grant all on table public.shared_reports to authenticated;
grant all on table public.shared_reports to service_role;
grant usage, select on sequence public.shared_reports_id_seq to authenticated;
grant usage, select on sequence public.shared_reports_id_seq to service_role;
