create table if not exists public.monthly_settlement_reports (
  id bigint generated by default as identity primary key,
  client_ids bigint[] not null default '{}',
  year_month text not null,
  title text not null,
  share_token text not null unique,
  screenshot_paths text[] not null default '{}',
  transactions jsonb not null default '[]'::jsonb,
  ocr_documents jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

create index if not exists monthly_settlement_reports_created_at_idx
  on public.monthly_settlement_reports (created_at desc);

create index if not exists monthly_settlement_reports_year_month_idx
  on public.monthly_settlement_reports (year_month);

create index if not exists monthly_settlement_reports_client_ids_idx
  on public.monthly_settlement_reports using gin (client_ids);

alter table public.monthly_settlement_reports enable row level security;

drop policy if exists "admin all monthly_settlement_reports" on public.monthly_settlement_reports;

create policy "admin all monthly_settlement_reports"
  on public.monthly_settlement_reports
  for all
  to authenticated
  using (true)
  with check (true);

grant all on table public.monthly_settlement_reports to authenticated;
grant all on table public.monthly_settlement_reports to service_role;
grant usage, select on sequence public.monthly_settlement_reports_id_seq to authenticated;
grant usage, select on sequence public.monthly_settlement_reports_id_seq to service_role;
